// Generated by gencpp from file robotarm_controller/AnglesConverter.msg
// DO NOT EDIT!


#ifndef ROBOTARM_CONTROLLER_MESSAGE_ANGLESCONVERTER_H
#define ROBOTARM_CONTROLLER_MESSAGE_ANGLESCONVERTER_H

#include <ros/service_traits.h>


#include <robotarm_controller/AnglesConverterRequest.h>
#include <robotarm_controller/AnglesConverterResponse.h>


namespace robotarm_controller
{

struct AnglesConverter
{

typedef AnglesConverterRequest Request;
typedef AnglesConverterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AnglesConverter
} // namespace robotarm_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotarm_controller::AnglesConverter > {
  static const char* value()
  {
    return "904e8346ace63ec441f6f58d8efc6687";
  }

  static const char* value(const ::robotarm_controller::AnglesConverter&) { return value(); }
};

template<>
struct DataType< ::robotarm_controller::AnglesConverter > {
  static const char* value()
  {
    return "robotarm_controller/AnglesConverter";
  }

  static const char* value(const ::robotarm_controller::AnglesConverter&) { return value(); }
};


// service_traits::MD5Sum< ::robotarm_controller::AnglesConverterRequest> should match
// service_traits::MD5Sum< ::robotarm_controller::AnglesConverter >
template<>
struct MD5Sum< ::robotarm_controller::AnglesConverterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotarm_controller::AnglesConverter >::value();
  }
  static const char* value(const ::robotarm_controller::AnglesConverterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotarm_controller::AnglesConverterRequest> should match
// service_traits::DataType< ::robotarm_controller::AnglesConverter >
template<>
struct DataType< ::robotarm_controller::AnglesConverterRequest>
{
  static const char* value()
  {
    return DataType< ::robotarm_controller::AnglesConverter >::value();
  }
  static const char* value(const ::robotarm_controller::AnglesConverterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotarm_controller::AnglesConverterResponse> should match
// service_traits::MD5Sum< ::robotarm_controller::AnglesConverter >
template<>
struct MD5Sum< ::robotarm_controller::AnglesConverterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotarm_controller::AnglesConverter >::value();
  }
  static const char* value(const ::robotarm_controller::AnglesConverterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotarm_controller::AnglesConverterResponse> should match
// service_traits::DataType< ::robotarm_controller::AnglesConverter >
template<>
struct DataType< ::robotarm_controller::AnglesConverterResponse>
{
  static const char* value()
  {
    return DataType< ::robotarm_controller::AnglesConverter >::value();
  }
  static const char* value(const ::robotarm_controller::AnglesConverterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTARM_CONTROLLER_MESSAGE_ANGLESCONVERTER_H
